base_url = "https://benpaternostro.com"
title = "Ben Paternostro"
description = "Resume and portfolio"
default_language = "en"
theme = "BelResume"
build_search_index = false

[extra]
site_name = "Ben Paternostro"
